### ISSUE TITLE
problem in lua decompiler please help!!

### ISSUE THREAD

**Issue by rksexe** [0BuRner/corona-archiver#5]
first of all thank you so much for making this tool. so i have extracted .car file and renamed to luac. and i decompiled it decompiled successfully but all the variables are like L101, L102 and not in the form of alphabets. so how can i decompile it so that all variables are like as original and not in form L101, L102,L103. [https://drive.google.com/file/d/1U72w7CRoGWy1wFiEdJMxn1ftVeq6H2eU/view?usp=sharing](url) here is my file

**Comment by 0BuRner** [comment]
Hi,
Thanks for your comment, I appreciate :-)
I have never coded anything in Lua so I'm far from being an expert but from what I've read it's not possible to keep variables original names :  https://reverseengineering.stackexchange.com/questions/9022/reversing-luac-is-there-a-way-to-get-proper-variable-names

> You can't retrieve function or variable names from compiled lua because the compiler strips it out of the compiled file, however you can make an educated guess by looking at what the decompiled lua code does.

Your issue is in fact not related to the corona-archiver script but to the Lua decompiler itself. To have a better answer you should therefore ask people who knows unluac tool :
- https://github.com/viruscamp/unluac
- https://github.com/HansWessels/unluac
- http://lua-users.org/lists/lua-l/2012-04/msg00606.html (official developer's email available)

Hope you will get better answer there. Keep us informed ! It can be useful for other users.

Regards,
